### ISSUE TITLE
Can it be installed in an already configured environment?

### ISSUE THREAD

**Issue by xjobex** [Zimbra-Community/shared-mailbox-toolkit#10]
Hello, what happens if I install shared-mailbox-toolkit on a Zimbra server where shared mailbox are already configured "the classical way", with personas and duplicated entries in FROM dropdown menu?

**Comment by barrydegraaff** [comment]
Yes, most certainly.

The dropdown menu in FROM should be de-duplicated for all your users.

Existing persona's should not be touched by shared-mailbox-toolkit. So they stay the same.

If you do not want the dropdown menu touched, you can opt not to install `Client Zimlet` when you run the installer.
