### ISSUE TITLE
Package newt is required on CentOS

### ISSUE THREAD

**Issue by seidler2547** [Zimbra-Community/shared-mailbox-toolkit#11]
On a plain CentoOS 7 install, the installer fails without any notice if the package `newt` that provides `/usr/bin/whiptail` is not installed.

**Comment by barrydegraaff** [comment]
How did you install centos... newt is pretty much there on very basic install...

**Comment by barrydegraaff** [comment]
newt added to the installer.

**Comment by seidler2547** [comment]
I think that was a LXC container template. probably a minimal CentOS image. Thanks for fixing.
