### ISSUE TITLE
Soap Actions

### ISSUE THREAD

**Issue by lsenecaux** [Zimbra-Community/shared-mailbox-toolkit#14]
Hy, 
First of all thank you for this zimlet. 
I will want to know if SOAP commands are available to manage shared mailbox ?
If no, is this planned ?
Regards,

**Comment by barrydegraaff** [comment]
Hello, 

While it is not meant to be a `public` API you can issue SOAP to the Admin UI like 
the zimlet does here: 
https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/master/tk_barrydegraaff_sharetoolkit_admin/ZaShareToolkitTab.js#L94 

So something like: 

var soapDoc = AjxSoapDoc.create("ShareToolkit", "urn:ShareToolkit", null); 
soapDoc.getMethod().setAttribute("action", " createShare orremoveShare "); 
soapDoc.getMethod().setAttribute("accounta"," Zimbra Account to share" ); 
soapDoc.getMethod().setAttribute("accountb"," Zimbra Account to give/remove share to" ); 
soapDoc.getMethod().setAttribute("skipPersonaCreation", " false "); 
soapDoc.getMethod().setAttribute("permissions"," rwixd see:https://wiki.zimbra.com/wiki/Zmmailbox#Permissions_.28modifyFolderGrant.29" ); 
var csfeParams = new Object(); 
csfeParams.soapDoc = soapDoc; 
csfeParams.asyncMode = true; 
csfeParams.callback = new AjxCallback(PutYourMethodHere); 
var reqMgrParams = {} ; 
resp = ZaRequestMgr.invoke(csfeParams, reqMgrParams); 



Hope that answers the question.

**Comment by lsenecaux** [comment]
We have internally developed a PHP management application (create, rename, lock, etc.) of generic mailboxes via the SOAP APIs.
I would like to try to integrate, in the same way, these mailboxes automatically into the registered account.

**Comment by barrydegraaff** [comment]
Request URL: 
[ https://zimbradev:7071/service/admin/soap/ShareToolkit | https://yourzimbraserver:7071/service/admin/soap/ShareToolkit ] 


<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Header><context xmlns="urn:zimbra"><userAgent name="ZimbraWebClient - GC63 (Linux)"/><session id="12"/><format type="js"/><csrfToken>0_27f87fc57124e6214f680489b6f6ca9f06d900b6</csrfToken></context></soap:Header><soap:Body><ShareToolkit xmlns="urn:ShareToolkit" action="createShare" accounta="example@zimbradev.barrydegraaff.tk" accountb="admin@zimbradev.barrydegraaff.tk" skipPersonaCreation="false" permissions="rwixd"/></soap:Body></soap:Envelope> 

Would share the example account with the admin account. 

You would also need to set ZM_ADMIN_AUTH_TOKEN cookie or some other way to authenticate. 

Anyway, the Zimbra Shared Mailbox toolkit is a `normal` Zimbra Admin Extension, it talks soap, so you 
should be able to solve that puzzle. 

In Google Chrome, hit f12 and go to the network tab, than try and make a share, and see the 
request to the server. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

+31 617 220 227 | skype: barrydegraaff.tk 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by lsenecaux** [comment]
Thank you for this clarification.
I think it will be very useful.

Regards,

**Comment by lsenecaux** [comment]
Great !
I can share generic mailboxes via PHP script.
However, it takes very long time to process (about 60s).
When I call SOAP APIs to create an account, it takes less than 3s.

**Comment by barrydegraaff** [comment]
Yep it is not fast, it is because multiple command need to start a java process, zmmailbox/zmprov and such.

Perhaps you can fire it asynchronous or just wait for it.

**Comment by lsenecaux** [comment]
One more thing...
When sharing, it creates a persona for each alias. 
How to avoid this?

**Comment by barrydegraaff** [comment]
It sounds like you are using personagen, that generates personas for each alias.
Otherwise it should only create 1 persona, perhaps your php fires the creation
of the share multiple times?

Check to make sure you use `action = createShare`

You can skip ALL persona creation by setting skipPersonaCreation = true


But double check your php, for loops, 


There is no loop here:
https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/master/bin/subzim#L80

**Comment by lsenecaux** [comment]
Okay, I'll see that.
Thanks again for your help
