### ISSUE TITLE
shared account not showed in imap

### ISSUE THREAD

**Issue by freemiumdev** [Zimbra-Community/shared-mailbox-toolkit#18]
Hi,
when I share an entire mailbox with another, the shared mailbox isn't listed and showed in imap client. In the client (Thunderbird) I've tried to update the subscribed folder but the shared mailbox isn't listed. Can you help me?
thanks

**Comment by barrydegraaff** [comment]
Maybe hit the refresh button an few times and restart thunderbird.
A screenshot:
https://superuser.com/questions/392320/how-can-i-force-thunderbird-to-reload-imap-folder-structure

If that does not work, try the CLI command `submachinegun` to share:
https://github.com/Zimbra-Community/shared-mailbox-toolkit#cli-commands

**Comment by freemiumdev** [comment]
I tried your advice but nothing, I do not see them.
Searching again for the web I have discerned that perhaps the problem is a Zimbra Bug and precisely this:

[bug 108880](https://bugzilla.zimbra.com/show_bug.cgi?id=108880)

I installed version 8.8.8 so I think I have the bug too.

**Comment by LKNickname** [comment]
I have the same problem and just wanted to ask if there is a solution/workaround for this issue.

When I share an entire mailbox via the toolkit it shows up in Zimbra but neither in Thunderbird nor Outlook (Mobile/Desktop).

I have recently upgraded to version 8.8.11 but it happened with 8.8.10 too.

Reinstalling the zimlet does not solve the issue and neither did both of your provided solution unfortunately.
