### ISSUE TITLE
One Folder not shared

### ISSUE THREAD

**Issue by mammut47** [Zimbra-Community/shared-mailbox-toolkit#19]
With sharing through shared-mailbox-toolkit some Folders are not shared. 
I think this is a Folder which was created through an imap-Client.
```
        Id  View      Unread   Msg Count  Path
----------  ----  ----------  ----------  ----------
       280  mess           0           0  /Ablage
    204426  mess           0           0  /test
```
Folder with Name "Ablage" and all subfolders are not shown.
Newly created Folders are shown. 
"test"-Folder is created after installation of shared-mailbox-toolkit. "test"-Folder is shown.

**Comment by barrydegraaff** [comment]
Zimbra is not 100% reliable sharing all folders.

Try submachinegun cli command

**Comment by mammut47** [comment]
As zimbra-user
usage: submachinegun <shared with account user mailbox> <shared mailbox>
Then its OK.
Many thanks for help
