### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by hands00me** [Zimbra-Community/shared-mailbox-toolkit#2]
Login error message:
An error occurred while initialising the zimlet “tk_barrydegraaff_sharetoolkit_client”. Please notify administrator.
ReferenceError: ZmComposeView is not defined 

how to remove this zimlet ?

**Comment by barrydegraaff** [comment]
rm -Rf /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_sharetoolkit_client

**Comment by barrydegraaff** [comment]
What version of zimbra is this?

**Comment by barrydegraaff** [comment]
Very sorry about this, I have not had that problem, as some of my other zimlets prevent it from happening on dev and prod here.

You can re-install, and all should be OK then! Thanks for reporting.
