### ISSUE TITLE
RFE: Production mode

### ISSUE THREAD

**Issue by adriangibanelbtactic** [Zimbra-Community/shared-mailbox-toolkit#21]
Can you please add an option to be able to install the zimlet in production mode?

Production mode means using:
```
/opt/zimbra/zimlets-deployed/tk_barrydegraaff_sharetoolkit_client
 ```
instead of:
```
/opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_sharetoolkit_client
```
?

Thank you.

**Comment by barrydegraaff** [comment]
It is not a good idea, as this is something you will want to force to be the same for all users. But you can of course create a ZIP file and deploy that way.

**Comment by adriangibanelbtactic** [comment]
> It is not a good idea, as this is something you will want to force to be the same for all users.
Yes, that's what zimlets are for.

> But you can of course create a ZIP file and deploy that way.
I know.

The other reason for wanting a ZIP is because I do not want this zimlet to be loaded in a RAM as a new jetty application every time a user logs in.

I suppose proper installed zimlet work as the zimbra and zimbraAdmin jetty applications. Those are loaded into RAM once (when the first user queries the zimbra app url or zimbra admin app url for the first time).

**Comment by barrydegraaff** [comment]
AFAIK the only difference is that a deployed zip file will extracted and then be compressed and merged with other javascript files. This reduces the amount of HTTP requests to the server and the amount of data transmitted over the network. So it is a bit faster. In addition more http caching is used.

I do not see what RAM has to do with this. Disadvantage of the zip-deploy is cache issues if one wants to deploy updates. Also shared-mailbox-toolkit is more a patch than a zimlet. Hence one should not want to see that in the cos settings. But you are free to do what you want.
