### ISSUE TITLE
Remove binaries from source code

### ISSUE THREAD

**Issue by adriangibanelbtactic** [Zimbra-Community/shared-mailbox-toolkit#22]
There appear to be some binaries in the source code. Some of them are in:

https://github.com/Zimbra-Community/shared-mailbox-toolkit/tree/master/extension/ShareToolkit/lib

Can you please remove the binaries and update the build instructions if needed?

Binaries should get wrapped in what's called releases.
Additionally if you supply a binary without its associated source code you might be violating GNU GPLv2 license.

Please check related documentation: https://help.github.com/articles/creating-releases/

Thank you very much!

**Comment by barrydegraaff** [comment]
No, because I really don't care about that.

In a perfect world, I would. But in a perfect world shared-mailbox-toolkit would make me a buck, but it does not.

**Comment by adriangibanelbtactic** [comment]
> The libraries you are referring to a just there, so one can build the shared-mailbox-toolkit
> from a development system. They are already in Zimbra, so the libraries on the repo
> do not get distributed to your zimbra server if you run the installer.

That's nice to know.

> To build shared-mailbox-toolkit you can open it in IntelliJ and hit the build option,
> yes it is better to have a maven or gnu make style build process. But I do not have
> the time to work on that, as 99% of the users just don't care about that.

Yeah, that would be better indeed. One day I might be interested in developing the zimlet and I might be scared of the fact of having to use IntelliJ UI.

> All my source code is here and all the dependencies as well as my are open source.

I'll try to clarify my satement.

1) Having 'your source code' here as you say is not legally enough.

Whenever you publish (publish means making something publicy available) https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/master/extension/ShareToolkit/lib/zimbrastore.jar you are probably redistributing a binary issued from GPLv2 source code and the license is quite clear on you having to redistribute its source code at the same time as the binary.

https://www.gnu.org/licenses/gpl-faq.en.html#DistributeWithSourceOnInternet

2) I, myself, don't like downloading binaries if I can avoid them. However if a binary is available from a trusted source I might use it. If the source code contains binaries too then it seems to like a poisoned gift.

I might open similar issues in other of your Zimbra related projects if I ever have to use them. When doing so I'll link to this issue so that I don't repeat myself and so that I don't waste your time.

Despite of the above I value your contribution to the Zimbra community and whenever I can I try to add some code to improve them.

Keep up your good work!
