### ISSUE TITLE
Disclaimers not longer working

### ISSUE THREAD

**Issue by adriangibanelbtactic** [Zimbra-Community/shared-mailbox-toolkit#23]
I have experienced that disclaimers ( https://wiki.zimbra.com/wiki/Steps_to_configure_per_domain_disclaimer_on_ZCS_8.5_and_higher_versions ) are no longer working after installing the zimlet as per default install instructions.

I'm not 100% sure on the former statement so I need to ask if you are installing  a jar that somehow overrides a default jar and somehow disables disclaimers.

Or if (this is going to be my next test) this is a secondary effect of running (probably Zimbra bug):

```
su - zimbra -c "zmprov mcf zimbraSmtpSendAddAuthenticatedUser TRUE
```
.

Thank you for any help you can provide.

**Comment by barrydegraaff** [comment]
It is probably not related, the shared mailbox toolkit effectively runs the zmprov/zmmailbox commands in:
https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/master/bin/subzim

But it does so only if the admin runs it from CLI or via the admin-ui. The JARs are just wrappers around the CLI command.

**Comment by adriangibanelbtactic** [comment]
Update about this issue: A ZCS upgrade to a newer version solved the problem.
