### ISSUE TITLE
Folders do not appear in share | NG incompatible?

### ISSUE THREAD

**Issue by claudioguolo** [Zimbra-Community/shared-mailbox-toolkit#26]
I have a problem:
I have mailbox A and mailbox B.
If account X in mailbox A accesses account Y in mailbox B - OK
If account Y in mailbox B accesses account X in mailbox A - Not OK, the shared folder does not appear in the client account. The send permission on account A's name works.
all accounts in server A accesses accounts in server A and like in servers B - OK
I need instructions on checking log or some other information to solve this problem.
PS. Accesses made in web interface.

Thank you.

Claudio

**Comment by barrydegraaff** [comment]
A share in a share?

Why not share the target mailbox directly to account Y? Shares in shares are not really a good idea.

**Comment by claudioguolo** [comment]
Sorry if it was not well understood, this was just a test I did, but at different times. The problem is that I can not share one account with another while they are in different mailboxes.

Thankful.

**Comment by barrydegraaff** [comment]
Sometimes Zimbra is not reliable when doing sharing.You can run the submachinegun script to fix folders not showing up on shares.

https://github.com/Zimbra-Community/shared-mailbox-toolkit#cli-commands
https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/master/bin/submachinegun

**Comment by claudioguolo** [comment]
I already performed this procedure as per the instructions I found in github.

**Comment by barrydegraaff** [comment]
When you first installed Zimbra on this server what was the version, and what version is it now?

**Comment by claudioguolo** [comment]
when I installed it was version 8.8.6 NET and it was normal.
It is now version 8.8.10 NET and does not work normal.
Along with 8.8.10 came the NG package, where it has a delegated authority function which I do not use since it only does persona and does not share folders.
I think maybe this NG might be interfering with something and will not let the Shared Toolkit function properly. But I did not find logs that would identify this.

**Comment by barrydegraaff** [comment]
Thanks for the info, since Shared Mailbox Toolkit is only tested on the Open Source edition, perhaps you ran into a bug.

**Comment by barrydegraaff** [comment]
You could try and run this script on the mailbox that does not show in the share
https://gist.github.com/barrydegraaff/a4b734e326e3c905a593095c3d38abed

Sometimes the I flag get set on folders, causing shares to misbehave.

The script does not do anything other then generate a list of commands to remove the flag. So you will have to copy-paste the output and run that from a separate bash file.

Beware, as this will break existing shares. Analyze the output before running.

**Comment by claudioguolo** [comment]
Hello,
I believe the problem has been solved.
An inconsistency was detected in the certificates of the mailbox servers, after correcting this the zimlet returned to function normally.
Thank you for your attention.
