### ISSUE TITLE
ERROR: service.INVALID_REQUEST (invalid request: can only be used with SOAP)

### ISSUE THREAD

**Issue by soriacom** [Zimbra-Community/shared-mailbox-toolkit#27]
Hello,
When i try to install this zimlet, i have this error. I'm newby, sorry. 
ERROR: service.INVALID_REQUEST (invalid request: can only be used with SOAP)
Do you have an idea?
Thanks for you time. 
Best

**Comment by barrydegraaff** [comment]
You need to use SSH to go to your Zimbra server, and then run as root:

      wget https://raw.githubusercontent.com/Zimbra-Community/shared-mailbox-toolkit/master/shared-mailbox-toolkit-installer.sh -O /tmp/shared-mailbox-toolkit-installer.sh
      chmod +rx /tmp/shared-mailbox-toolkit-installer.sh
      /tmp/shared-mailbox-toolkit-installer.sh
