### ISSUE TITLE
Check for whiptail

### ISSUE THREAD

**Issue by techsolo** [Zimbra-Community/shared-mailbox-toolkit#29]
Hi, 

I was installing this (great tool!) but I had to check the script to see why it didn't do anything. To find out it needs whiptail. I see you already check for git and zip, maybe you should add whiptail as well.

Kind regards,

Solo

**Comment by barrydegraaff** [comment]
Thanks, I have simplified some checks and it should work now https://github.com/Zimbra-Community/shared-mailbox-toolkit/commit/1653c5e4d6fea47be9bd100447c7be82f851a5b7
