### ISSUE TITLE
[RFE] Evaluate if it's possible to fix/comply to the "zimbraPrefDelegatedSendSaveTarget" setting

### ISSUE THREAD

**Issue by mrCine** [Zimbra-Community/shared-mailbox-toolkit#3]
See https://bugzilla.zimbra.com/show_bug.cgi?id=106844 and https://bugzilla.zimbra.com/show_bug.cgi?id=107020, basically Personas don't seem to follow the SendSaveTarget setting.

(Reported by Cerri on IRC, opener of bug 106844 above)

**Comment by barrydegraaff** [comment]
Thanks, I can confirm this bug. Maybe I can change 
https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/master/tk_barrydegraaff_sharetoolkit_client/tk_barrydegraaff_sharetoolkit_client.js#L51

Take care of all the logic myself, take some of the info from the persona, and some from the sendAs... its unfortunate though.

**Comment by barrydegraaff** [comment]
this bug is in 8.6 and 8.7.1 so maybe it was never implemented, like as with sendAs... so I guess we need to update 107020 to point the devs to the change in sendAs that was done in 8.6 to add this feature.

**Comment by barrydegraaff** [comment]
related: https://bugzilla.zimbra.com/show_bug.cgi?id=103970

**Comment by barrydegraaff** [comment]
possible work-around is outgoing message filter:

https://bugzilla.zimbra.com/show_bug.cgi?id=106762

**Comment by barrydegraaff** [comment]
some zmprov to add a filter

      /opt/zimbra/bin/zmmailbox -z -m $1 addFilterRule '[SUSPECTED SPAM]' active any header 'subject' contains '[SUSPECTED SPAM]' fileinto '/Junk'

**Comment by barrydegraaff** [comment]
https://wiki.zimbra.com/wiki/Email_Rules_Migration

**Comment by nomennesc-io** [comment]
subzim now automatically adds an outgoing filter that saves mail in the appropriate sent folder
