### ISSUE TITLE
Suggest adding Drafts folder to the list of shared folders

### ISSUE THREAD

**Issue by davidkillingsworth** [Zimbra-Community/shared-mailbox-toolkit#30]
Great idea to make this extension.  We support a few zimbra installs that have many shared mailboxes that numerous individuals use and this task causes alot of admin time.

I suggest adding the Drafts folders to the list of folders already shared with this extension.

**Comment by barrydegraaff** [comment]
I have just added the Drafts folder to subzim/unsubzim per your request.

Even though it should already have worked, I know Zimbra can be buggy sometimes when
creating / -root shares.
