### ISSUE TITLE
Suggestion: Fill in the "When composing, replying to or forwarding mesages in folders(s)

### ISSUE THREAD

**Issue by davidkillingsworth** [Zimbra-Community/shared-mailbox-toolkit#31]
I note that on the persona, the extension fills in the email address that was shared in the "when replying or forwarding messages sent to" field, but the field right below it is not set.

"When composing, replying to or forwarding mesages in folders(s)" 

Is there a reason that the inbox of the mailbox that was shared to the user is not filled in here?

**Comment by barrydegraaff** [comment]
Yes, the reason that the folder option is not checked, is because the 
`When replying or forwarding messages sent to:` -option is checked 

and that will make the reply trigger the correct persona.
