### ISSUE TITLE
Migration Export/Import

### ISSUE THREAD

**Issue by claudioguolo** [Zimbra-Community/shared-mailbox-toolkit#32]
Hello
If I need to do a migration from all accounts in my environment to another Zimbra server pool, how can I export the shares relationship so that I can generate a script for the new pool configuration?
Is there a specific table in MySql / MariaDB where are these settings stored or a tool for this migration?
Thank you.

**Comment by barrydegraaff** [comment]
You can use Zextras incremental migration 
[ https://wiki.zextras.com/wiki/ZxBackup:_Incremental_migration_with_ZeXtras_Backup | https://wiki.zextras.com/wiki/ZxBackup:_Incremental_migration_with_ZeXtras_Backup ] 

You can also use 
/opt/zimbra/bin/zmmailbox -z -m $MAILBOX gaf 
But I would not recommend that 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
