### ISSUE TITLE
Missing personas when sharing to a distribution list

### ISSUE THREAD

**Issue by dani** [Zimbra-Community/shared-mailbox-toolkit#36]
When I share a mailbox A to a user B, everything is working correctly. User B sees A's mailbox. And user B can send as A (in which case the sent item goes to A's Sent folder as expected).

But when I share a mailbox A to a distribution list C, it's not as smooth. Permissions are granted, but members of DL C must "Accept" the share (in their preference) before the mailbox appears in the tree. Also, the personas are not created : members of DL C can't send as A, and no filter is created.

**Comment by barrydegraaff** [comment]
Actually, it was never intended to share with DL's...

So if DL's are in the drop-down list, I guess we need to remove that option

**Comment by dani** [comment]
Yes, DL's appear in the drop down, can be selected, and at least the permission part seems to work. I'm surprised it's not intended to work with DL. The description of the zimlet starts with "Do you have generic mailboxes for you sales department, helpdesk or info@yourcompany.com". Granting permission on user level for this kind of usage is not realistic (especially as there's no way from the GUI to list the existing grants). How hard would it be to fully support DL's ?

**Comment by barrydegraaff** [comment]
Yes a distribution list is not a mailbox... but I guess that is all Zimbra slang :-p 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by dani** [comment]
Yes, DL's are not mailbox, but are Zimbra's concept of user groups. As such, it's normal not to be able to share a DL with someone else, but it should be possible to share a mailbox with a DL (BTW right now, DL's appear in both the account to share and the "with" drop-downs)

**Comment by livingsilver94** [comment]
I also think it'd be handy to allow to share a mailbox to a distribution list: it's easier to add and remove employees from a group rather than share/unshare as people come and go.
This wanted behavior is also implemented in Zarafa, IIRC.

**Comment by barrydegraaff** [comment]
fixed auto completion https://github.com/Zimbra-Community/shared-mailbox-toolkit/commit/7b23b440aedbb992a03f4c10fdbe91ef4229a41c
