### ISSUE TITLE
Remove plugin

### ISSUE THREAD

**Issue by allexpetrov** [Zimbra-Community/shared-mailbox-toolkit#37]
Hello, 

Not clear how to remove the plugin. Is there any instruction on how to remove it? 

Regards,
Aleksejs!

**Comment by barrydegraaff** [comment]
rm -Rf /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_sharetoolkit_client 
rm -Rf /opt/zimbra/lib/ext/ShareToolkit 
su - zimbra -c "zmzimletctl undeploy tk_barrydegraaff_sharetoolkit_admin" 

Restart mailbox 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
