### ISSUE TITLE
Feature request: Add option to enable "Send on Behalf Of"

### ISSUE THREAD

**Issue by VeselaHouba** [Zimbra-Community/shared-mailbox-toolkit#38]
Hello Barry,

First of all: Great work, we love this toolkit, it saves us tons of work :)
But we miss one feature: When delegates are created, they have only the "Send As" right. 
When using web GUI everything is fine, but when using Outlook with Zimbra Connector, we receive error that user doesn't have right to send on behalf of ...

Would it be possible to add option to enable this feature, or enable it by default?

Thanks a lot in advance.

**Comment by barrydegraaff** [comment]
Do you know what zmprov command would solve this issue? 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by VeselaHouba** [comment]
```
zmprov grr account shared_account@domain.com usr user_of_share@domain.com sendOnBehalfOf
```
Does the tick for me

**Comment by barrydegraaff** [comment]
if you always want to use it this way, you can add the command in

/usr/local/sbin/unsubzim
and
/usr/local/sbin/subzim

I will probably not add it as an option in the near future.

**Comment by VeselaHouba** [comment]
Fair enough, thank you.

Just for reference here is what I changed, works fine.

subzim
```
@@ -87,6 +87,7 @@ then
 else
    NAME=`/opt/zimbra/bin/zmprov ga $MAILBOX displayName|egrep '^displayName:'|sed -e 's/^displayName: //'`
    echo "grr account $MAILBOX usr $SUBSCRIBER sendAs" >> "${PROFFILE}"
+   echo "grr account $MAILBOX usr $SUBSCRIBER sendOnBehalfOf" >> "${PROFFILE}"
    echo "deleteIdentity $SUBSCRIBER $PERSONA" >> "${PROFFILE}"
    echo "createIdentity $SUBSCRIBER $PERSONA zimbraPrefFromAddress $MAILBOX zimbraPrefWhenSentToAddresses $MAILBOX zimbraPrefWhenSent
    echo "dofrl \"$PERSONA.sent\"" >> "${BOXSFILE}"
```

unsubzim
```
@@ -65,6 +65,7 @@ then
    echo "Persona creation/deletion skipped per user request."
 else
    echo "rvr account $MAILBOX usr $SUBSCRIBER sendAs" >> "${PROFFILE}"
+   echo "rvr account $MAILBOX usr $SUBSCRIBER sendOnBehalfOf" >> "${PROFFILE}"
    echo "deleteIdentity $SUBSCRIBER $PERSONA" >> "${PROFFILE}"
    echo "dofrl \"$PERSONA.sent\"" >> "${BOXSFILE}"
 fi
```
```
