### ISSUE TITLE
Installed - get ldap error listing available mailboxes

### ISSUE THREAD

**Issue by sanddweller** [Zimbra-Community/shared-mailbox-toolkit#39]
Upon installing the Shared Mailbox Toolkit, then accessing the admin page to use it,
the mailbox selection fields display an error accessing ldap.

I have ldaps running on port 636.
```
#zmlocalconfig -e ldap_url=ldaps://mail.xxxxxx.com:636
#zmlocalconfig -e ldap_master_url=ldaps://mail.xxxxxx.com:636
#zmlocalconfig -e ldap_starttls_supported=0
#zmlocalconfig -e ldap_port=636

```
![shareToolkit](https://user-images.githubusercontent.com/5096641/66713475-7b503780-edbc-11e9-96df-76b64f28de20.JPG)

**Comment by barrydegraaff** [comment]
Did you install on a single-server installation? If not, is it installed on the mailbox? 

Try running /usr/local/sbin/subzim from the cli to debug, is the DNS correct? 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
