### ISSUE TITLE
zimbra 8.8.12 to 8.8.15 upgrade

### ISSUE THREAD

**Issue by EdG91** [Zimbra-Community/shared-mailbox-toolkit#41]
Hello,
I would like just to know if there is no issue when upgrading from zimbra 8.8.12 to 8.8.15 for shared mailbox toolkit ?
The share mailbox toolkit was installed first in 8.8.12 ; I would to perform the zimbra upgrade toward 8.8.15
Best Regards

**Comment by barrydegraaff** [comment]
Yeah works fine!

**Comment by EdG91** [comment]
Thank you for your answer.

Another request, is there any command to get list of users for a shared mailbox ?
I am thinking something similar in cyrus, with the command lam.sharemaibox (list all users with rights e.g. lrsip)

**Comment by barrydegraaff** [comment]
You would have to script that, using `zmprov gaf` and `zmprov ga $i zimbraSharedItem` an example of a script that removes shares can help you there:
https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/master/bin/removeshares#L41
