### ISSUE TITLE
mailfrom header wrong

### ISSUE THREAD

**Issue by ezoNetworks** [Zimbra-Community/shared-mailbox-toolkit#42]
Hi, I was having alignment issues with SPF and discovered that when I sent an email from a persona the mailfrom header was actually displaying the delegated account email and not the persona email. The from header was correctly displaying the persona account email.

**Comment by barrydegraaff** [comment]
please share your email headers

**Comment by ezoNetworks** [comment]
Thanks for looking at this Barry. 

Below are the headers: mailfrom shows as paul@pauljrocha.com and should show paul@ezonetworks.com, paul@pauljrocha.com is the designated account and paul@ezonetworks.com is the shared account. 

![Screenshot_2019-12-13 Original Message](https://user-images.githubusercontent.com/55464865/70805143-42195100-1d86-11ea-9f79-15af85ec7734.png)

**Comment by ezoNetworks** [comment]
Hi, Barry, did the headers help?

**Comment by barrydegraaff** [comment]
haven't had time to look yet, sorry

**Comment by barrydegraaff** [comment]
The headers are indeed misaligned, even though Google reports dkim and spf pass on your headers.

Are you going into the spam box?

There are 2 possible work-arounds, log-in using 2 accounts and send out mail. That way you are not using shared mailboxes.

Or set up a milter filter that rewrites the message headers in such a way that all is aligned. This is not that easy though. Here is an example, but you will need to take some time to fit it to your needs:
https://github.com/Zimbra-Community/mailing-lists/wiki/Set-mailing-list-email-headers-with-Milter

I will add a message in the README about this problem

**Comment by vquiering** [comment]
Hi,
try setting `zimbraSmtpRestrictEnvelopeFrom` in Zimbra on to `False`.

    zmprov desc -a zimbraSmtpRestrictEnvelopeFrom
    zimbraSmtpRestrictEnvelopeFrom
        If TRUE, the address for MAIL FROM in the SMTP session will always be
        set to the email address of the account. If FALSE, the address will be
        the value of the Sender or From header in the outgoing message, in
        that order.
    
                   type : boolean
                  value : 
               callback : 
              immutable : false
            cardinality : single
             requiredIn : 
             optionalIn : cos,account
                  flags : accountInfo,accountInherited
               defaults : TRUE
                    min : 
                    max : 
                     id : 1077
        requiresRestart : 
                  since : 6.0.5
        deprecatedSince : 

Does this solve your issue?

**Comment by vquiering** [comment]
If anyone else is looking for a solution, `zimbraSmtpRestrictEnvelopeFrom` sets the correct return path. I just tested it myself.
