### ISSUE TITLE
Persona/Filter Name Issue on multiple domains

### ISSUE THREAD

**Issue by yomono** [Zimbra-Community/shared-mailbox-toolkit#43]
Hi! This tool works great, is greate to have it!
But i found this problem:
If i have two accounts from different domain, but the same name (ie: sales@domain1.com and sales@domain2.com), is impossible to use the toolkit to share both.
This is because of the automatic name the toolkit assign to the new Persona and the Sent Folder Filter.
They are just called "sales.persona" and "sales.persona.sent". Naturally, when i try to share the second account, it overrides the first one, because the name is the same.
Not only that, but also if i manually rename the persona and the filter, it stills causing troubles and overriding them (i guess maybe some internal stored info, idk).
It would be great if the persona and the filter be the hole account name (sales@domain1.com.persona and sales@domain2.com.persona). 
Is there any way to archieve this? Even if i have to modify the code, i have no problem with that, but can you give me a lead of where to modify it would be greate.
Thank you in advance

**Comment by barrydegraaff** [comment]
Yeah, this should be supported, 

You can take a look at: 
[ https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/master/bin/subzim#L54 | https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/master/bin/subzim#L54 ] 
[ https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/master/bin/unsubzim#L47 | https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/master/bin/unsubzim#L47 ] 
[ https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/master/bin/personagen#L44 | https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/master/bin/personagen#L44 ] 

See also /usr/local/sbin on your server. 

I think it is a matter of changing 
PERSONA="${MAILBOX%@*}.persona" 

To 
PERSONA="${MAILBOX}.persona" 

But probably @ is not allowed in filter names or persona names, so you would have to replace @ with _ or so 
in that bash line. 

Lemme know what works. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by yomono** [comment]
Barry, you are amazing!
It worked like a charm.
I just modify "${MAILBOX%@*}.persona" to "${MAILBOX}.persona" on subzim and unsubzim files, and from "PERSONA="${i%@*}.persona" to "PERSONA="${i}.persona" on the personagen file, and thats it!

Also, i can confirm you that both persona and filter DOES accept @ in the names, so no problem with that. Thank you again.

PS: Is the first time i open an issue on github. Should i select "Close and comment" since its resolved?

**Comment by barrydegraaff** [comment]
Now we need to make some changes, so that this becomes the default behavior for new shares.
While also allowing to still remove/update the previously created shares and settings from the older versions.

I am leaving this open till I have time to implement and test it.

**Comment by barrydegraaff** [comment]
Support for multiple domains added.
