### ISSUE TITLE
MailServiceException.NO_SUCH_MSG when sending mail with attachment via shared account

### ISSUE THREAD

**Issue by olympic1337** [Zimbra-Community/shared-mailbox-toolkit#44]
When I send an email via a shared account with an attachment I receive an error message saying "No such mail" and the following error in the logs:
`
ExceptionId:qtp366590980-202:https://zimbra.xxxxxxx/service/soap/SendMsgRequest:1579133001213:d5d6e20119bd0072
Code:mail.NO_SUCH_MSG Arg:(itemId, IID, "3965")
	at com.zimbra.cs.mailbox.MailServiceException.NO_SUCH_MSG(MailServiceException.java:219)
`

When removing the attachment everything works well, also when sending the mail including the attachment via the own account.
Zimbra version is 8.8.15_GA_3895.

Thanks very much for your help!

**Comment by barrydegraaff** [comment]
This is part of an upstream regression: 
[ https://forums.zimbra.org/viewtopic.php?f=13&t=67507&hilit=broken+personas | https://forums.zimbra.org/viewtopic.php?f=13&t=67507&hilit=broken+personas ] 



Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by olympic1337** [comment]
@barrydegraaff many thanks for your help! Indeed, after replacing the zimbrastore.jar file with the one provided in the thread you mentioned, everything is working fine again. Thank you very much!

**Comment by milealf** [comment]
Hello, can you please help me?
I have the error
com.zimbra.cs.mailbox.MailServiceException$NoSuchItemException: no such message: 175763
at com.zimbra.cs.mailbox.MailServiceException.NO_SUCH_MSG(MailServiceException.java:220) ~[zimbrastore.jar:8.8.15_GA_4562]

The error occurs due to signatures with broken links, is there a way to deactivate the error message?
