### ISSUE TITLE
How to see shared mailbox

### ISSUE THREAD

**Issue by MyTheValentinus** [Zimbra-Community/shared-mailbox-toolkit#45]
Hello

How to see all share active ?  I search some command and in the zimbra dministration but how to see who have a X mailbox shared ?

Thanks

**Comment by barrydegraaff** [comment]
zmmailbox -z -m [ mailto:user@example.com | user@example.com ] gaf

**Comment by dominix** [comment]
there is something like this oneliner  that works for me :
`for U in $(/opt/zimbra/bin/zmprov -l gaa |grep -vE '^virus-quarantine|^spam\.|^ham\.|^galsync'|sort);do echo $U;/opt/zimbra/bin/zmmailbox -z -m $U gaf |awk '$5~/@/ && $6 ~/@/';done`

**Comment by dominix** [comment]
```
for U in $(/opt/zimbra/bin/zmprov -l gaa |grep -vE '^virus-quarantine|^spam\.|^ham\.|^galsync'|sort)
do
     echo $U
    /opt/zimbra/bin/zmmailbox -z -m $U gaf |awk '$5~/@/ && $6 ~/@/'
done
```
