### ISSUE TITLE
LDAP Bind error

### ISSUE THREAD

**Issue by MyTheValentinus** [Zimbra-Community/shared-mailbox-toolkit#46]
Hello,

I just update today to the latest version before post this issue.

The autocomplete doen't work, and when i fill the entire input with emails, no error, but share is not shared ^^

In the share settings of user preferences panel the share not appear

![image](https://user-images.githubusercontent.com/6104498/73830916-bcee6d80-4805-11ea-911a-66c05098ae2e.png)

Thanks

**Comment by barrydegraaff** [comment]
Do you have a multi server set-up? 

try and run 
/usr/local/sbin/acctalias 

[ https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/master/bin/acctalias | https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/master/bin/acctalias ] 

It seems some issue in your environment set-up. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by MyTheValentinus** [comment]
Hello,
No single server
Result of command:
```
> /usr/local/sbin/acctalias
zimbra@mail:~$ /usr/local/sbin/acctalias
ldap_bind: Confidentiality required (13)
	additional info: confidentiality required
```
Ubuntu 16.04 with zimbra 8.8.12.GA.3794

**Comment by barrydegraaff** [comment]
8.8.12 is not supported by Shared Mailbox Toolkit, 

maybe you have a self signed cert, and you can 

In /etc/ldap/ldap.conf, set: 
TLS_REQCERT never 


Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by MyTheValentinus** [comment]
Ho, okay, will it be supported one day?
I have a letsencrypt certificate for ldap too

**Comment by barrydegraaff** [comment]
No, because 8.8.12 is EOL. The latest version of Zimbra 8.8.15 is supported. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by MyTheValentinus** [comment]
I just upgrade to 8.8.15, but the same error, ldap error

Thanks

**Comment by barrydegraaff** [comment]
did you put: 

In /etc/ldap/ldap.conf, set: 
TLS_REQCERT never 

??? 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by MyTheValentinus** [comment]
Yes is set.

```
root@mail:/etc/apt/sources.list.d# cat /etc/ldap/ldap.conf 
#
# LDAP Defaults
#

# See ldap.conf(5) for details
# This file should be world readable but not world writable.

#BASE	dc=example,dc=com
#URI	ldap://ldap.example.com ldap://ldap-master.example.com:666

#SIZELIMIT	12
#TIMELIMIT	15
#DEREF		never

# TLS certificates (needed for GnuTLS)
TLS_CACERT	/etc/ssl/certs/ca-certificates.crt
TLS_REQCERT never

```

**Comment by barrydegraaff** [comment]
try 

bash -x /usr/local/sbin/acctalias

**Comment by MyTheValentinus** [comment]
Here:

```
zimbra@mail:~$ bash -x /usr/local/sbin/acctalias
++ whoami
+ WHO=zimbra
+ '[' zimbra '!=' zimbra ']'
+ [[ -x /opt/zimbra/common/bin/ldapsearch ]]
+ sort
+ awk '{print $2}'
+ grep '^mail'
++ awk '{print $3}'
++ /opt/zimbra/bin/zmlocalconfig -s zimbra_ldap_userdn
++ /opt/zimbra/bin/zmlocalconfig -s zimbra_ldap_password
++ awk '{print $3}'
++ /opt/zimbra/bin/zmlocalconfig ldap_url
++ awk '{print $3}'
+ /opt/zimbra/common/bin/ldapsearch -LLL -x -Duid=zimbra,cn=admins,cn=zimbra -PASSWORD -H ldap://mail.XXXXXXXXXXX.XX:389
ldap_bind: Confidentiality required (13)
	additional info: confidentiality required

```

**Comment by barrydegraaff** [comment]
Well it seems your ldapsearch command does not know the correct credentials 
to talk to your ldap. 

Which should work, as we load the credentials using zmlocalconfig. 

Did you configure some kind of special authentication? Or maybe weird characters in the password. 

I unfortunately cannot debug this remotely. I suggest you set up a test VM with Zimbra and then install 
shared mailbox toolkit and compare the difference. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by MyTheValentinus** [comment]
Hello,
I found the solution:

To patch your script you need to check if `ldap_starttls_required` is set to true, and if is true append `-Z` to your ldapsearch command.
`/opt/zimbra/common/bin/ldapsearch -LLL -x -Duid=zimbra,cn=admins,cn=zimbra -wXXXXXXXX -H ldap://mail.XXXXX.net:389`
TO
`/opt/zimbra/common/bin/ldapsearch -LLL -x -Duid=zimbra,cn=admins,cn=zimbra -wXXXXXXXX -H ldap://mail.XXXXX.net:389 -Z`

Thanks

**Comment by barrydegraaff** [comment]
Thanks, I will integrate that soon! 

https://wiki.zimbra.com/wiki/TLS/STARTTLS_Localconfig_Values#ldap_starttls_required 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by barrydegraaff** [comment]
This has been fixed in https://github.com/Zimbra-Community/shared-mailbox-toolkit/commit/7b23b440aedbb992a03f4c10fdbe91ef4229a41c

**Comment by MyTheValentinus** [comment]
Good ! Thanks
