### ISSUE TITLE
persona does not add name to FROM header

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/shared-mailbox-toolkit#5]
when using persona's from created by shared-mailbox-toolkit, the name of the user is not added to the FROM header in the email, but they are displayed on the preferences page.

in the from headeri  is:
 (jblack@zombra.com)
expected:
John Black (jblack@zombra.com)

**Comment by nomennesc-io** [comment]
the displayName of the user is now added in the FROM header
