### ISSUE TITLE
Install script errors out due to unavailable zmlocalconfig command

### ISSUE THREAD

**Issue by neelabhg** [Zimbra-Community/shared-mailbox-toolkit#50]
Hi @barrydegraaff ,

Thanks for this excellent toolkit!

When I last ran the installer, it crashed at the following line with the error that `zmlocalconfig` is not found:
https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/d33d9682d7b710855548f384d7c18f5df5b4298f/shared-mailbox-toolkit-installer.sh#L134

Thankfully, since this line is at the end of the script, the installation went just fine. I only had to run the last line (deleting the temp folder) myself.

Since this script is supposed to be run as root (I used `sudo`), I think you can use 
```sh
SESSION_LIMIT=$(su - zimbra -c "zmlocalconfig zimbra_session_limit_admin" | awk '{print $3}')
```
instead, just like you've done in the rest of the script.

**Comment by barrydegraaff** [comment]
thanks for reporting, fixed it.
