### ISSUE TITLE
Add folder condition to "reply with this persona" options

### ISSUE THREAD

**Issue by maxxer** [Zimbra-Community/shared-mailbox-toolkit#52]
Currently the plugin sets to use the shared account when replying to mails with the account as the recipient.

It would be more valuable, IMHO, to set the reply rule for the newly created folder. That is if you reply to a mail into a shared folder where the user is in BCC it wouldn't use that account as sender but the main one. While using the folder as selector for the persona would be more precise.

Maybe it could be an option when sharing the account? Being able to select one or both the methods?

**Comment by barrydegraaff** [comment]
Hmm not that easy to implement, shared mailbox toolkit uses the features available from the persona settings, it does not implement anything new in Zimbra.

**Comment by maxxer** [comment]
What new feature? That's an option in persona setting

![immagine](https://user-images.githubusercontent.com/240201/85988260-1478ba00-b9ef-11ea-9bab-7adedd04ac73.png)

**Comment by barrydegraaff** [comment]
Owh sorry about that, if it works, it is probably better than the current behavior, if you can update subzim in the bin folder and send a PR we can merge it.
