### ISSUE TITLE
Shared accounts automatically becoming inaccessible

### ISSUE THREAD

**Issue by sammyscarz** [Zimbra-Community/shared-mailbox-toolkit#55]
Hi,

We have noticed recently that accounts shared through the mailbox toolkit have been randomly becoming inaccessible to some users. 

For example, a user with the shared mailbox "shared@example.com" will be able to see all mail and send from this mail account after being given permissions through the toolkit, but only days later this mail account will show up as inaccessible to the user through the web client and have a line crossed through it like so: ~~shared@example.com~~. This occurs without any prompting from any administrator or the user themselves.

Is this a common issue? Is there something that triggers this to occur?

Any help will be much appreciated, thank you.

**Comment by barrydegraaff** [comment]
This is not a known issue, most likely someone is revoking the shares manually. The strike trough indicates the share has been revoked.
