### ISSUE TITLE
[Sent] and [Junk] are not shared / shown

### ISSUE THREAD

**Issue by tfohlmeister** [Zimbra-Community/shared-mailbox-toolkit#6]
Thanks for this great plugin which works pretty well in most parts for me!

I got this strange issue with our main account which I try to root share with another user. Both accounts - _info_ (the account to share) and _user_ (the account to get access to _info_) - are regular zimbra mailboxes/users. When I run as zimbra: `subzim user@mydomain.com info@mydomain.com` I receive the following errors:
`ERROR: account.NO_SUCH_IDENTITY (no such identity: info.persona)`
`ERROR: zclient.CLIENT_ERROR (can't find rule: [Ljava.lang.String;@7fb48179)`

I can confirm the root share was successful created as the _info_ user now has a new share called USER_ROOT with type Mail-Folder and user _user_ can now can see all folders in Mail, Contacts, Calender and Tasks from _info_ **except** for the two mail folders _Sent_ and _Junk_.

This also makes the auto-created filter rule fixing #3 (thanks!) fail, because the /Sent folder is not available.

**Any idea what causes this behavior or how to debug it?**

Another suggestion: The above errors are only displayed when run from CLI, the web backend admin tool just shows a success. Maybe you could also output those errors over there?

**Comment by barrydegraaff** [comment]
This is a bug in Zimbra, **what version are you on**? The error messages, can be safely ignored, they just are a result of trying to remove something that is not there. (but will be next time you run this)

In the mean time, I explicitly added /Sent and /Junk to subzim and unsubzim cli script. Please re-install the cli components, and try again.

**Comment by tfohlmeister** [comment]
Thanks, adding those folders explicitly fixed the issue. I am on Ubuntu 14.04.5 LTS and Zimbra Collaboration 8.7.1 by the way.
