### ISSUE TITLE
Documentation request: Update procedure

### ISSUE THREAD

**Issue by hboetes** [Zimbra-Community/shared-mailbox-toolkit#61]
Hi Barry,

thanks for this wonderful plugin. Makes life so much easier.

I was wondering though:
- how should we update if your plugin gets updates?
- what should we do after a Zimbra update?

**Comment by barrydegraaff** [comment]
On Zimbra update -> Nothing

On Shared Mailbox Toolkit -> re-download an re-run the installer

**Comment by hboetes** [comment]
OK, thanks.
