### ISSUE TITLE
RFH: notifications for shared calendars

### ISSUE THREAD

**Issue by hboetes** [Zimbra-Community/shared-mailbox-toolkit#62]
From the Zimbra forum: https://forums.zimbra.org/viewtopic.php?t=28396

> Notifications are generally reserved for the owner of the calendar. We use Exchanges model for calendar sharing, which means that on a shared cal, you won't get a notification.
> To get one, the event must be on a local calendar, so the organizer should share an event with you so you can get a notification.

Well that's rather disappointing. Can you think of an elegant solution for this problem?

**Comment by hboetes** [comment]
bump.

**Comment by barrydegraaff** [comment]
Work around example: create an account sales-team@example.com and share the calendar with salesperson1@example.com and  salesperson2@example.com. Then you can create a distribution list that has salesperson1@example.com and  salesperson2@example.com in it. And configure the sales-team@example.com to forward all email to the distribution list.

You can then set the email notification on any appointment, and that way everyone will be notified.

This is not something that shared mailbox toolkit can fix. You can use dynamic distribution lists to automate things a bit.

**Comment by hboetes** [comment]
Thanks for the suggestion.
