### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by LVTTony** [Zimbra-Community/shared-mailbox-toolkit#64]
We have been using Subzim but it suddenly said command not found with no system changes.
I am on CentOS 7 with all updates.

I used the auto-installer as root to reinstall the toolkit, but it said: 
`com.zimbra.common.zclient.ZClientException: invoke Connection refused, server: localhost`

I fixed that by running `zmlocalconfig -e zimbra__zmprov_default_soap_server=MailBoxServerIP`

Now it says:
```
java.io.IOException: No such file or directory
at java.base/java.io.UnixFileSystem.createFileExclusively (Native Method)
etc...
```

**Comment by barrydegraaff** [comment]
Not sure what it can be, it works here.
