### ISSUE TITLE
Delegated admin can access all accounts

### ISSUE THREAD

**Issue by KlugFR** [Zimbra-Community/shared-mailbox-toolkit#65]
Hi.

If you enable the admin-zimlet access for a dletegated admin (admin of a few domains), the delegated admin can see all the accounts that are created on the infrastructure. 

Is there a way to limit the available accounts to the accounts of his domains?

**Comment by barrydegraaff** [comment]
This is not implemented at this time and would take quite some effort, so unfortunately: no.

**Comment by KlugFR** [comment]
For the records, this is supposed to work since version 0.6 (december 2023)
