### ISSUE TITLE
persona fromName scrambles non ascii characters

### ISSUE THREAD

**Issue by tfohlmeister** [Zimbra-Community/shared-mailbox-toolkit#7]
Auto-created personas have problems with non-ascii characters in the fromName.

In my example german Umlaute (ä, ö, ü) which were there in the original account name are now scrambled:
<img width="488" alt="screen shot 2016-11-23 at 10 29 09" src="https://cloud.githubusercontent.com/assets/4696987/20556640/58f95632-b168-11e6-9682-f8437de90c56.png">
The original account was named _Geschäftsstelle_.

**Comment by barrydegraaff** [comment]
Well most likely this is garbeled by subzim/personagen

I suspect it has to do with bash not understanding utf-8, http://superuser.com/questions/378394/why-cant-bash-display-symbols-like-%C3%A6-%C3%B8-and-%C3%A5

Maybe you can see if you can fix the bash script, or otherwise we will look into it next week.

**Comment by barrydegraaff** [comment]
see /usr/local/sbin/subzim

**Comment by barrydegraaff** [comment]
I have not been able to reproduce this, created an account with display name Geschäftsstelle, and shared that to another account, that just worked.


![2016-11-30-092536_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4353213/20744950/fdfbc612-b6de-11e6-9727-13ebe07889dc.png)

**Comment by barrydegraaff** [comment]
The part of the code that is responsible for getting the display name is in the cli:
https://github.com/Zimbra-Community/shared-mailbox-toolkit/blob/master/bin/subzim#L42

So the Admin UI does not matter (it passes usernames to the cli as arguments)

What is your Zimbra and OS version? If you want me to debug your server remotely you can get a support subscription: https://www.powercraft.nl/zetalliance/
