### ISSUE TITLE
Unwanted headers

### ISSUE THREAD

**Issue by blessendor** [Zimbra-Community/shared-mailbox-toolkit#9]
Installed all components.

Mail sent from a shared person.

Headers contains original user info (same as with default Zimbra sharing mailboxes/folders options).

https://monosnap.com/file/9aAX2c0zdXR5LeSDAvdnSY7OAuYWwt

https://monosnap.com/file/rgsJbGgFnRbG5OoHrO9aR1UQAOjL3Q

Is this a little bug or my missunderstanding about functionality?

Thanks

**Comment by blessendor** [comment]
Found your original description:

"An additional header is added to the email to identify the user sending email from a shared mailbox. For example it can help finding out what sales person was sending out mail from sales@myzimbra.com."

So it looks like my missunderstanding.

My users wants to have a several accounts, shared with own main, and don't want to have a main address in the headers, just a shared address information.

Yor addon is good for teamwork, really. 
But not for my current case (task). =)

**Comment by barrydegraaff** [comment]
If you do not want to show the x-authenticated header, 
you can re-run the installer and disable the corresponding option.

Or 
   su - zimbra -c "zmprov mcf zimbraSmtpSendAddAuthenticatedUser FALSE"
and 
su - zimbra -c "zmmtactl restart"

So you can enable/disable, not sure what the problem is. Its optional.

**Comment by barrydegraaff** [comment]
add the word `optional` to readme

**Comment by blessendor** [comment]
x-authenticated header removed ( su - zimbra -c "zmprov mcf zimbraSmtpSendAddAuthenticatedUser FALSE")

But header "Return-Path"- still there.

Do you know how to remove it too?

**Comment by barrydegraaff** [comment]
maybe a cache issue, when choosing the FROM address, are you selecting one that ends with .persona?

**Comment by barrydegraaff** [comment]
also try with a new message thread.

**Comment by blessendor** [comment]
Yes, I use persona.
Always with new message (thread) for testing.
Always reloading web page.
Don't know where this header is applied.

**Comment by barrydegraaff** [comment]
When you shared the account, did you select an alias?

So in the admin UI, share the account with account.

What you selected in the UI, where those aliasses or accounts?

**Comment by barrydegraaff** [comment]
what zimbra version ?

**Comment by blessendor** [comment]
When I make share I use my aliased address. 

Zimbra 8.7.4.

**Comment by blessendor** [comment]
New test with accound demo2 whithout any aliases.

Shared from demo1.

Delivered-To: black@gmail.com
Received: by 10.100.181.43 with SMTP id q40csp70360pjb;
        Fri, 10 Mar 2017 08:46:55 -0800 (PST)
X-Received: by 10.223.173.53 with SMTP id p50mr17873306wrc.112.1489164415884;
        Fri, 10 Mar 2017 08:46:55 -0800 (PST)
Return-Path: <demo2@domain.com.ua>
Received: from skynet.domain.com.ua (skynet.domain.com.ua. [relay])
        by mx.google.com with ESMTPS id b76si13534515wrd.273.2017.03.10.08.46.55
        for <black@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 10 Mar 2017 08:46:55 -0800 (PST)
Received-SPF: pass (google.com: domain of demo2@domain.com.ua designates relay as permitted sender) client-ip=relay;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of demo2@domain.com.ua designates relay as permitted sender) smtp.mailfrom=demo2@domain.com.ua
Received: from netbox.domain.com.ua ([144.76.72.182] helo=mail.domain.kiev.ua) by skynet.domain.com.ua with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256) (envelope-from <demo2@domain.com.ua>) id 1cmNgs-0001PR-Sq for black@gmail.com; Fri, 10 Mar 2017 18:46:54 +0200
Received: from localhost (localhost.localdomain [127.0.0.1]) by mail.domain.kiev.ua (Postfix) with ESMTP id 4709A140004 for <black@gmail.com>; Fri, 10 Mar 2017 18:44:26 +0200 (EET)
Received: from mail.domain.kiev.ua ([127.0.0.1]) by localhost (mail.domain.kiev.ua [127.0.0.1]) (amavisd-new, port 10032) with ESMTP id 10DN403e9Y5R for <black@gmail.com>; Fri, 10 Mar 2017 18:44:26 +0200 (EET)
Received: from localhost (localhost.localdomain [127.0.0.1]) by mail.domain.kiev.ua (Postfix) with ESMTP id 1B97C1400B8 for <black@gmail.com>; Fri, 10 Mar 2017 18:44:26 +0200 (EET)
X-Amavis-Modified: Mail body modified (using disclaimer) - mail.domain.kiev.ua
X-Virus-Scanned: amavisd-new at mail.domain.kiev.ua
Received: from mail.domain.kiev.ua ([127.0.0.1]) by localhost (mail.domain.kiev.ua [127.0.0.1]) (amavisd-new, port 10026) with ESMTP id WvaAqqIYPZlM for <black@gmail.com>; Fri, 10 Mar 2017 18:44:26 +0200 (EET)
Received: from mail.domain.kiev.ua (mail.domain.kiev.ua [192.168.182.5]) by mail.domain.kiev.ua (Postfix) with ESMTP id 025A8140004 for <black@gmail.com>; Fri, 10 Mar 2017 18:44:26 +0200 (EET)
Date: Fri, 10 Mar 2017 18:44:25 +0200 (EET)
From: Demo 1 <demo1@domain.com.ua>
To: black@gmail.com
Message-ID: <1482793244.0.1489164265785.JavaMail.zimbra@domain.com.ua>
Subject: Test demo2 from demo1
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit
X-Originating-IP: [192.168.182.5]
X-Mailer: Zimbra 8.7.4_GA_1730 (ZimbraWebClient - GC56 (Mac)/8.7.4_GA_1730)
Thread-Index: Ps1s2sA5CFkcYtgboP0ETplpLPCLGw==
Thread-Topic: Test demo2 from demo1

Test headers
(null)

**Comment by blessendor** [comment]
Account demo2 sent mail from shared demo1.
Return-path still contain demo2.


Delivered-To: black@gmail.com
Received: by 10.100.181.43 with SMTP id q40csp70360pjb;
        Fri, 10 Mar 2017 08:46:55 -0800 (PST)
X-Received: by 10.223.173.53 with SMTP id p50mr17873306wrc.112.1489164415884;
        Fri, 10 Mar 2017 08:46:55 -0800 (PST)
Return-Path: <demo2@domain.com.ua>
Received: from skynet.domain.com.ua (skynet.domain.com.ua. [relay])
        by mx.google.com with ESMTPS id b76si13534515wrd.273.2017.03.10.08.46.55
        for <black@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 10 Mar 2017 08:46:55 -0800 (PST)
Received-SPF: pass (google.com: domain of demo2@domain.com.ua designates relay as permitted sender) client-ip=relay;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of demo2@domain.com.ua designates relay as permitted sender) smtp.mailfrom=demo2@domain.com.ua
Received: from netbox.domain.com.ua ([111.111.111.111] helo=mail.domain.kiev.ua) by skynet.domain.com.ua with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256) (envelope-from <demo2@domain.com.ua>) id 1cmNgs-0001PR-Sq for black@gmail.com; Fri, 10 Mar 2017 18:46:54 +0200
Received: from localhost (localhost.localdomain [127.0.0.1]) by mail.domain.kiev.ua (Postfix) with ESMTP id 4709A140004 for <black@gmail.com>; Fri, 10 Mar 2017 18:44:26 +0200 (EET)
Received: from mail.domain.kiev.ua ([127.0.0.1]) by localhost (mail.domain.kiev.ua [127.0.0.1]) (amavisd-new, port 10032) with ESMTP id 10DN403e9Y5R for <black@gmail.com>; Fri, 10 Mar 2017 18:44:26 +0200 (EET)
Received: from localhost (localhost.localdomain [127.0.0.1]) by mail.domain.kiev.ua (Postfix) with ESMTP id 1B97C1400B8 for <black@gmail.com>; Fri, 10 Mar 2017 18:44:26 +0200 (EET)
X-Amavis-Modified: Mail body modified (using disclaimer) - mail.domain.kiev.ua
X-Virus-Scanned: amavisd-new at mail.domain.kiev.ua
Received: from mail.domain.kiev.ua ([127.0.0.1]) by localhost (mail.domain.kiev.ua [127.0.0.1]) (amavisd-new, port 10026) with ESMTP id WvaAqqIYPZlM for <black@gmail.com>; Fri, 10 Mar 2017 18:44:26 +0200 (EET)
Received: from mail.domain.kiev.ua (mail.domain.kiev.ua [192.168.182.5]) by mail.domain.kiev.ua (Postfix) with ESMTP id 025A8140004 for <black@gmail.com>; Fri, 10 Mar 2017 18:44:26 +0200 (EET)
Date: Fri, 10 Mar 2017 18:44:25 +0200 (EET)
From: Demo 1 <demo1@domain.com.ua>
To: black@gmail.com
Message-ID: <1482793244.0.1489164265785.JavaMail.zimbra@domain.com.ua>
Subject: Test demo2 from demo1
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit
X-Originating-IP: [192.168.182.5]
X-Mailer: Zimbra 8.7.4_GA_1730 (ZimbraWebClient - GC56 (Mac)/8.7.4_GA_1730)
Thread-Index: Ps1s2sA5CFkcYtgboP0ETplpLPCLGw==
Thread-Topic: Test demo2 from demo1

Test headers
(null)

**Comment by barrydegraaff** [comment]
https://bugzilla.zimbra.com/show_bug.cgi?id=106191

**Comment by barrydegraaff** [comment]
https://bugzilla.zimbra.com/show_bug.cgi?id=77665

https://bugzilla.zimbra.com/show_bug.cgi?id=102931

I am afraid that the return-path behavior is hardcoded in Java, I will follow up on this next week.

**Comment by barrydegraaff** [comment]
I tried to reproduce this on 8.7.4 and 8.6 but I do not get the Return-Path header in my mail.

It has to be some persona setting or cache issue. But to test out, I probably need to debug it from your server.

If you want me to debug it for you, maybe you can consider getting a support subscription
https://www.powercraft.nl/zetalliance/   (yes there is an invalid ssl certificate on that)
